In [2]:
import numpy as np

In [ ]:
def u_solver(mesh):
    r=0.01;
    sigma=0.2;
    K=100;
    T=1;
    R=300;
    dt=T/mesh;
    dx=R/mesh;

    U=zeros((mesh-1,mesh));
    B=ones(mesh-1,1);
    a=ones(mesh-1,1);
    b=ones(mesh-1,1);
    c=ones(mesh-1,1);

    for i=1:1:mesh-1
        a(i)=-0.5*dt*sigma^2*i^2;
        b(i)=1+dt*(r+r*i+sigma^2*i^2);
        c(i)=dt*(-r*i-0.5*sigma^2*i^2);
        U(i,1)=max(0,K-i*dx);
    end
    a(1)=0;c(mesh-1)=0;
    B=U(:,1);
    B(1,1)=U(1,1)-(-0.5*dt*sigma^2)*K*exp(-r*(T-dt));
    for j=2:1:mesh
        U(:,j)=TDMAsolver(a,b,c,B);
        k=1:mesh-1;
        U(:,j)=max(U(:,j),max(0,K-k*dx)');
        B=U(:,j);
        B(1,1)=U(1,1)-(-0.5*dt*sigma^2)*K*exp(-r*(T-dt));
    end

In [4]:
def e_solver(mesh):
    price1 = u_solver(mesh)
    price2 = u_solver(mesh*2)
    p1 = price1[:, mesh]
    p2 = price2[2:2:2*mesh-2,2*mesh]
    return max(abs(p1-p2));

In [5]:
def e_order(mesh):
    return np.log(e_solver(mesh)/e_solver(mesh*2))/np.log(2)

In [152]:
mesh = 10

r=0.01;
sigma=0.2;
K=100.0;
T=1.0;
R=300.0;
dt=T/mesh;
dx=R/mesh;

U=np.zeros((mesh-1,mesh))
B=np.ones((mesh-1,1))
a=np.ones((mesh-1,1))
b=np.ones((mesh-1,1))
c=np.ones((mesh-1,1))

for i in range(mesh-1):
    a[i] = -0.5 * dt * sigma**2 * (i+1)**2
    b[i] = 1 + dt * (r + r*i + sigma** 2 * (i+1)**2);
    c[i] = dt * (-r * (i+1) - 0.5 * sigma**2 * (i+1)**2)
    U[i,0]=max(0,K-(i+1)*dx);
a[0] = 0
c[-1] = 0
B = U[:,0]
B[0] = U[0, 0] - (-0.5*dt*sigma**2)*K*np.exp(-r*(T-dt))
for j in range(1, mesh-1):
    print(U[:, j])
#     U(:,j)=TDMAsolver(a,b,c,B);
#     k=1:mesh-1;
#     U(:,j)=max(U(:,j),max(0,K-k*dx)');
#     B=U(:,j);
#     B(1,1)=U(1,1)-(-0.5*dt*sigma^2)*K*exp(-r*(T-dt));
# end

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [149]:
B

array([ 70.19820808,  40.        ,  10.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,   0.        ])

In [135]:
b

array([[ 1.005],
       [ 1.018],
       [ 1.039],
       [ 1.068],
       [ 1.105],
       [ 1.15 ],
       [ 1.203],
       [ 1.264],
       [ 1.333]])

In [136]:
c

array([[-0.003],
       [-0.01 ],
       [-0.021],
       [-0.036],
       [-0.055],
       [-0.078],
       [-0.105],
       [-0.136],
       [-0.171]])

In [137]:
U

array([[ 70.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 40.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [140]:
c

array([[-0.003],
       [-0.01 ],
       [-0.021],
       [-0.036],
       [-0.055],
       [-0.078],
       [-0.105],
       [-0.136],
       [ 0.   ]])