In [11]:
import numpy as nn
from scipy.spatial.distance import mahalanobis

In [41]:
height = np.array([220, 210,190,190])
weight = np.array([110, 90, 110, 90])

In [66]:
cov = np.cov(height, weight)
print(cov)

[[ 225.           33.33333333]
 [  33.33333333  133.33333333]]


In [65]:
inv_conv = np.linalg.inv(cov)
print(inv_conv)

[[ 0.00461538 -0.00115385]
 [-0.00115385  0.00778846]]


In [75]:

distances = np.zeros((4,4))
for i in range(4):
    for j in range(4):
        distances[i][j] = mahalanobis([height[i], weight[i]], [height[j], weight[j]], inv_conv)


In [76]:
print(distances)

[[ 0.          1.76504522  2.03809866  2.42582262]
 [ 1.76504522  0.          2.42582262  1.35873244]
 [ 2.03809866  2.42582262  0.          1.76504522]
 [ 2.42582262  1.35873244  1.76504522  0.        ]]


In [84]:
for j in range(4):
        print("{}th person distanace to average ".format(j+1))
        print(mahalanobis([height[j], weight[j]], [200, 100], inv_conv))


1th person distanace to average 
1.47087101354
2th person distanace to average 
1.21291131009
3th person distanace to average 
1.21291131009
4th person distanace to average 
1.00479619059
